project:
  type: book
  output-dir: "docs"

website:
  favicon: "img/logos/favicon.ico"
  reader-mode: true
  comments: 
    hypothesis:
      theme: clean
      openSidebar: true

book:
  title: "Manual de LaTeX"
  author: "Alfredo Sánchez Alberca"
  date: "1/6/2022"
  output-file: "manual-latex"
  image: cover.png
  cover-image: img/logos/logo-latex.png
  sharing: [twitter, linkedin]
  downloads: [pdf, epub]
  favicon: "img/logos/favicon.ico"
  sidebar: 
    logo: img/logos/aprendeconalf.png
    tools:
      - icon: house-fill
        href: https://aprendeconalf.es
  open-graph: true
  twitter-card: 
    site: "@aprendeconalf"
  chapters:
    - index.qmd
    - introduccion.qmd
    - estructura.qmd
    - secciones.qmd
    - formateo.qmd
    - listas.qmd
    - tablas.qmd
    - figuras.qmd
    - formulas.qmd
    #- referencias.qmd
    #- bibliografia.qmd
    
#bibliography: references.bib


format:
  html:
    theme: cosmo
    dark: darkly
    light: flatly
  pdf:
    documentclass: scrreport
  epub:
    cover-image: cover.png



